### ISSUE TITLE
Common K-Mers

### ISSUE THREAD

**Issue by drob2727** [refresh-bio/PHIST#6]
Is there a minimum number of common k-mers to have a high quality host prediction or is 1 accurate?

**Comment by Changhai996** [comment]
>10 kmer sounds suitable for that (https://doi.org/10.1038/s41564-022-01144-6)

**Comment by aziele** [comment]
Hi @drob2727,

I don't have a clear answer for that. Several molecular mechanisms may result in the retention of identical sequences in the genomes of the phage and its host. Such sequences can correspond to prophages (several thousand common _k_-mers), horizontally-transferred genes (hundreds of common _k_-mers), and short sequences such as CRISPR spacers and integration sites (1-10 common _k_-mers). If you care about a high recall of hosts' predictions, one _k_-mer will probably be the best choice.
